"
"                       __   _(_)_ __ ___  _ __ ___
"                       \ \ / / | '_ ` _ \| '__/ __|
"                        \ V /| | | | | | | | | (__
"                       (_)_/ |_|_| |_| |_|_|  \___|
"
" Author: fefas me@fefas.net
" Source: http://github.com/fefas/dotfiles/tree/master/vim
"
" Reference: joedicastro http://github.com/joedicastro/dotfiles/tree/master/vim

" neobundle {{{

set nocompatible     " no to the total compatibility with the ancient vi

" neobundle auto-installation and setup {{{

let iCanHazNeoBundle=1
let neobundle_readme=expand($HOME.'/.vim/bundle/neobundle.vim/README.md')
if !filereadable(neobundle_readme)
   echo "Installing NeoBundle.."
   echo ""
   silent !mkdir -p $HOME/.vim/bundle
   silent !git clone https://github.com/Shougo/neobundle.vim $HOME/.vim/bundle/neobundle.vim
   let iCanHazNeoBundle=0
endif

" Call NeoBundle
if has('vim_starting')
   set rtp+=$HOME/.vim/bundle/neobundle.vim/
endif
call neobundle#begin(expand($HOME.'/.vim/bundle/'))

" is better if NeoBundle rules NeoBundle (needed!)
NeoBundle 'Shougo/neobundle.vim'

" }}}

" plugins install {{{

"Layout
NeoBundle 'flazz/vim-colorschemes'
NeoBundle 'bling/vim-airline'
NeoBundle 'ntpeters/vim-better-whitespace'
NeoBundle 'Yggdroot/indentLine'

" Syntax
NeoBundleLazy 'elzr/vim-json', {'filetypes' : 'json'}
NeoBundle 'scrooloose/syntastic'
NeoBundle 'evidens/vim-twig'
NeoBundle 'cakebaker/scss-syntax.vim'

" Git
NeoBundle 'airblade/vim-gitgutter'
NeoBundle 'tpope/vim-fugitive'
NeoBundleLazy 'gregsexton/gitv',
               \ {'depends':['tpope/vim-fugitive'],
               \  'autoload':{'commands':'Gitv'}}

" Markdown
"NeoBundleLazy 'joedicastro/vim-markdown'
"NeoBundleLazy 'joedicastro/vim-markdown-extra-preview'
NeoBundleLazy 'JamshedVesuna/vim-markdown-preview'

" }}}

call neobundle#end()

" auto install the plugins {{{

" First-time plugins installation
if iCanHazNeoBundle == 0
    echo "Installing Bundles, please ignore key map error messages"
    echo ""
    set nomore
    NeoBundleInstall
endif

" Check if all of the plugins are already installed, in other case ask if we
" want to install them (useful to add plugins in the .vimrc)
NeoBundleCheck

" }}}

" }}} neobundle

" functions {{{

" make a dir if no exists {{{

function! MakeDirIfNoExists(path)
    if !isdirectory(expand(a:path))
        call mkdir(expand(a:path), "p")
    endif
endfunction

" }}}

" }}} functions

" vim config {{{

scriptencoding utf-8
set encoding=utf-8              " setup the encoding to UTF-8
set ls=2                        " status line always visible
set go-=T                       " hide the toolbar
set go-=m                       " hide the menu
set visualbell                  " turn on the visual bell
set cursorline                  " highlight the line under the cursor
set fillchars+=vert:│           " better looking for windows separator
set ttyfast                     " better screen redraw
set title                       " set the terminal title to the current file
set showcmd                     " shows partial commands
set hidden                      " hide the inactive buffers
set ruler                       " sets a permanent rule
set lazyredraw                  " only redraws if it is needed
set autoread                    " update a open file edited outside of Vim
set ttimeoutlen=0               " toggle between modes almost instantly
set backspace=indent,eol,start  " defines the backspace key behavior
set virtualedit=all             " to edit where there is no actual character
set more                        " to show pages using `more` in command outpouts
set number                      " show line number
set mouse=a                     " enable mouse events

" quick basic commands (save, exit etc) {{{

nnoremap <Leader>11 :qa!<CR>

nnoremap <Leader>w  :w<CR>
nnoremap <Leader>W  :wa<CR>

nnoremap <Leader>q  :q<CR>
nnoremap <Leader>Q  :qa<CR>

" }}}

" backup {{{

set backup
set noswapfile
set backupdir=$HOME/.vim/tmp/backup/
set undodir=$HOME/.vim/tmp/undo/
set directory=$HOME/.vim/tmp/swap/
set viminfo+=n$HOME/.vim/tmp/viminfo

silent! call MakeDirIfNoExists(&undodir)
silent! call MakeDirIfNoExists(&backupdir)
silent! call MakeDirIfNoExists(&directory)

" }}}

" tabs, space and wrapping {{{

filetype plugin indent on      " enable indent size for file type

set expandtab                  " spaces instead of tabs
set tabstop=3                  " a tab = four spaces
set shiftwidth=3               " number of spaces for auto-indent
set softtabstop=3              " a soft-tab of four spaces
set autoindent                 " set on the auto-indent

au FileType php setl sw=4 sts=4 et
au FileType html setl sw=2 sts=2 et
au FileType twig setl sw=2 sts=2 et
au FileType svg setl sw=2 sts=2 et
au FileType xml setl sw=2 sts=2 et
au FileType css setl sw=2 sts=2 et
au FileType scss setl sw=2 sts=2 et
au FileType sass setl sw=2 sts=2 et

" set formatoptions=qrn1ct
set textwidth=80
set colorcolumn=81

" }}}

" get off the cursor keys {{{

nnoremap <up> <nop>
nnoremap <down> <nop>
nnoremap <left> <nop>
nnoremap <right> <nop>
inoremap <up> <nop>
inoremap <down> <nop>
inoremap <left> <nop>
inoremap <right> <nop>

" }}}

" fast window split and moves {{{

nnoremap <Leader>v <C-w>v
nnoremap <Leader>s <C-w>s

nnoremap <C-h> <C-w>h
nnoremap <C-j> <C-w>j
nnoremap <C-k> <C-w>k
nnoremap <C-l> <C-w>l

" }}}

" cut/paste to/from clipboard  {{{

map <Leader>y "*y
map <Leader>p "*p

" }}}

" colorscheme {{{

syntax enable                  " enable the syntax highlight
set background=dark            " set a dark background
set t_Co=256                   " 256 colors for the terminal
if has('gui_running')
    colorscheme seoul
else
    colorscheme seoul256
endif

au BufNewFile,BufRead *.phpt setlocal ft=php

" }}}

" }}} vim config

" plugins setup {{{

" airline {{{

set noshowmode

let g:airline_theme='powerlineish'
let g:airline_powerline_fonts=1
let g:airline#extensions#branch#enabled = 1
let g:airline#extensions#whitespace#enabled = 1
let g:airline#extensions#hunks#non_zero_only = 1

" }}}

" better whitespace {{{
"
highlight ExtraWhitespace ctermbg=red

" }}}

" json {{{

let g:vim_json_syntax_conceal = 0

" }}}

" syntastic {{{

set statusline+=%#warningmsg#
set statusline+=%{SyntasticStatuslineFlag()}
set statusline+=%*

let g:syntastic_always_populate_loc_list = 1
let g:syntastic_auto_loc_list = 0
let g:syntastic_check_on_open = 1
let g:syntastic_check_on_wq = 0

" }}}

" indent line {{{

let g:indentLine_enabled = 1
let g:indentLine_char = '|'
let g:indentLine_noConcealCursor=0

" }}}

" git {{{

nnoremap :Gst :Gstatus
nnoremap :Gco :Gcommit
nnoremap :Gch :Git checkout
nnoremap :Gps :Git push
nnoremap :Gpu :Git pull

nnoremap :Gv :Gitv --all

let g:Gitv_OpenHorizontal = 'auto'
let g:Gitv_WipeAllOnClose = 1
let g:Gitv_DoNotMapCtrlKey = 1
let g:Gitv_WrapLines = 1

autocmd FileType git set nofoldenable

" }}}

" markdown {{{

let vim_markdown_preview_github=1
let vim_markdown_preview_hotkey='<C-p>'
let vim_markdown_preview_browser='Google Chrome'

" }}}

" }}} plugins setup
